services:
  db:
    image: postgres
    container_name: postgres
    env_file: ".env.docker"
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis
    container_name: redis

  app:
    build: .
    image: hotels-api
    container_name: web-app
    env_file: ".env.docker"
    depends_on:
      - db
      - redis
    command: ./docker/app.sh
    ports:
      - "8000:8000"

  celery:
    image: hotels-api
    container_name: celery
    env_file: ".env.docker"
    environment:
      - NULL_POOL=1
    depends_on:
      - redis
    command: celery -A app.tasks.worker:worker worker --loglevel=INFO

  celery-beat:
    image: hotels-api
    container_name: celery-beat
    env_file: ".env.docker"
    environment:
      - NULL_POOL=1
    depends_on:
      - redis
    command: celery -A app.tasks.worker:worker beat --loglevel=INFO

  flower:
    image: hotels-api
    container_name: flower
    env_file: ".env.docker"
    environment:
      - NULL_POOL=1
    depends_on:
      - redis
    command: celery -A app.tasks.worker:worker flower
    ports:
      - "5555:5555"

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ./prometheus.yaml:/etc/prometheus/prometheus.yaml:ro
      - prometheus-data:/var/lib/prometheus/data
    command:
      - --config.file=/etc/prometheus/prometheus.yaml
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana
    container_name: grafana
    volumes:
      - grafana-data:/var/lib/grafana/data
    ports:
      - "3000:3000"

volumes:
  db-data:
  prometheus-data:
  grafana-data:
