"""Create bookings table.

Revision ID: dc114aa5926e
Revises: 7898385cb572
Create Date: 2024-05-04 17:32:20.857431+00:00

"""

from typing import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "dc114aa5926e"
down_revision: str | None = "7898385cb572"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "bookings",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("date_from", sa.Date(), nullable=False),
        sa.Column("date_to", sa.Date(), nullable=False),
        sa.Column("price", sa.Integer(), nullable=False),
        sa.Column(
            "total_days",
            sa.Integer(),
            sa.Computed("date_to - date_from"),
            nullable=False,
        ),
        sa.Column(
            "total_cost",
            sa.Integer(),
            sa.Computed("(date_to - date_from) * price"),
            nullable=False,
        ),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("room_id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("TIMEZONE('UTC', NOW())"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("TIMEZONE('UTC', NOW())"),
            nullable=False,
        ),
        sa.CheckConstraint("date_from < date_to", name="bookings_date_range_check"),
        sa.CheckConstraint("price >= 1", name="bookings_price_positive_check"),
        sa.ForeignKeyConstraint(
            ["room_id"],
            ["rooms.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("bookings")
    # ### end Alembic commands ###
