"""Create users table.

Revision ID: 0ead1ba398c0
Revises: 1ead8edb6df4
Create Date: 2024-05-03 22:13:43.948101+00:00

"""

from typing import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "0ead1ba398c0"
down_revision: str | None = "1ead8edb6df4"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("email", sa.String(), nullable=False),
        sa.Column("hashed_password", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("users")
    # ### end Alembic commands ###
