"""Add timestamps to users.

Revision ID: 3e11d1555e35
Revises: 0ead1ba398c0
Create Date: 2024-05-03 22:33:38.235071+00:00

"""

from typing import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "3e11d1555e35"
down_revision: str | None = "0ead1ba398c0"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("TIMEZONE('UTC', NOW())"),
            nullable=False,
        ),
    )
    op.add_column(
        "users",
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("TIMEZONE('UTC', NOW())"),
            nullable=False,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "updated_at")
    op.drop_column("users", "created_at")
    # ### end Alembic commands ###
