"""Create hotels table.

Revision ID: 1ead8edb6df4
Revises: 
Create Date: 2024-05-03 14:51:28.009200+00:00

"""

from typing import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "1ead8edb6df4"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "hotels",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("location", sa.String(), nullable=False),
        sa.Column("stars", sa.SmallInteger(), nullable=False),
        sa.Column("services", sa.JSON(), nullable=True),
        sa.CheckConstraint("stars BETWEEN 1 AND 5", name="hotels_stars_range_check"),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("hotels")
    # ### end Alembic commands ###
