"""Add image_name to hotels.

Revision ID: 1ed5da60f065
Revises: dc114aa5926e
Create Date: 2024-06-21 15:58:27.804399+00:00

"""

from typing import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "1ed5da60f065"
down_revision: str | None = "dc114aa5926e"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("hotels", sa.Column("image_name", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("hotels", "image_name")
    # ### end Alembic commands ###
