"""Add role to users.

Revision ID: a25dd99277b3
Revises: 1ed5da60f065
Create Date: 2024-06-26 21:01:14.648017+00:00

"""

from typing import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "a25dd99277b3"
down_revision: str | None = "1ed5da60f065"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

role_enum = sa.Enum("USER", "ADMIN", name="role")


def upgrade() -> None:
    role_enum.create(op.get_bind())
    op.add_column(
        "users",
        sa.Column("role", role_enum, nullable=True),
    )
    op.execute("UPDATE users SET role = 'USER'")
    op.alter_column("users", "role", nullable=False)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "role")
    # ### end Alembic commands ###
    role_enum.drop(op.get_bind())
